### ISSUE TITLE
报告一个问题，还有为什么不传AUR

### ISSUE THREAD

**Issue by xausky** [mzz2017/deepin-wechat-for-arch#1]
```
sed -i "s/\/opt\/deepinwine/LANG=zh_CN.UTF-8 \/opt\/deepinwine/" /opt/deepinwine/apps/Deepin-WeChat/run.sh
```
应改为
```
sed -i "s/\/opt\/deepinwine/LANG=zh_CN.UTF-8 \/opt\/deepinwine/" opt/deepinwine/apps/Deepin-WeChat/run.sh
```
提交了 PR #2 
比AUR上的那个 BUG少，能传上去就好

**Comment by mzz2017** [comment]
已修复，谢谢

**Comment by mzz2017** [comment]
> ```
> sed -i "s/\/opt\/deepinwine/LANG=zh_CN.UTF-8 \/opt\/deepinwine/" /opt/deepinwine/apps/Deepin-WeChat/run.sh
> ```
> 
> 应改为
> 
> ```
> sed -i "s/\/opt\/deepinwine/LANG=zh_CN.UTF-8 \/opt\/deepinwine/" opt/deepinwine/apps/Deepin-WeChat/run.sh
> ```
> 
> 提交了 PR #2
> 比AUR上的那个 BUG少，能传上去就好

因为这个pkg是从deepin-wechat这个pkg改的，而且我嫌麻烦……

**Comment by xausky** [comment]
总之谢了，现在就用的这个
